ALTER TABLE "Resume"
ADD COLUMN "parsedData" JSONB,
ADD COLUMN "skills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "experienceYears" DOUBLE PRECISION,
ADD COLUMN "domain" TEXT,
ADD COLUMN "education" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "certifications" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
