export function buildJobExtractionPrompt(rawText: string) {
  return [
    'Analyze the Job Description. Extract ALL skills, technologies, requirements, and',
    'qualifications mentioned — be exhaustive. Do not summarize or limit the lists.',
    'Return JSON only.',
    'No markdown.',
    'No explanations.',
    'No extra text.',
    '',
    'Extract these fields:',
    '1. jobTitle',
    '2. jobSummary',
    '3. requiredSkills',
    '4. preferredSkills',
    '5. requiredExperience',
    '6. domains',
    '7. responsibilities',
    '8. keywords',
    '9. aiRequirements',
    '10. cloudRequirements',
    '',
    'Use this exact JSON shape:',
    '{',
    '  "jobTitle": "",',
    '  "jobSummary": "",',
    '  "requiredSkills": ["string"],',
    '  "preferredSkills": ["string"],',
    '  "requiredExperience": 0,',
    '  "domains": ["string"],',
    '  "responsibilities": ["string"],',
    '  "keywords": ["string"],',
    '  "aiRequirements": ["string"],',
    '  "cloudRequirements": ["string"]',
    '}',
    '',
    'If a field is unknown, use an empty string, 0, or an empty array as appropriate.',
    '',
    'Job Description:',
    rawText,
  ].join('\n');
}
