export const SKILL_ALIASES: Record<string, string> = {
  nodejs: 'Node.js',
  'node js': 'Node.js',
  'node.js': 'Node.js',
  node: 'Node.js',
  reactjs: 'React',
  'react js': 'React',
  'react.js': 'React',
  react: 'React',
  js: 'JavaScript',
  javascript: 'JavaScript',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  postgres: 'PostgreSQL',
  postgresql: 'PostgreSQL',
  mongodb: 'MongoDB',
  mongo: 'MongoDB',
  expressjs: 'Express',
  'express js': 'Express',
  'express.js': 'Express',
  express: 'Express',
  aws: 'AWS',
  'amazon web services': 'AWS',
  'amazon web services (aws)': 'AWS',
  'aws (amazon web services)': 'AWS',
  'aws services': 'AWS',
  'aws service': 'AWS',
  cicd: 'CI/CD',
  'ci/cd': 'CI/CD',
  'ci cd': 'CI/CD',
  'ci/cd pipeline': 'CI/CD',
  'ci/cd pipelines': 'CI/CD',
  'ci cd pipeline': 'CI/CD',
  'ci cd pipelines': 'CI/CD',
  'continuous integration': 'CI/CD',
  'continuous integration and continuous deployment': 'CI/CD',
  'continuous integration/continuous deployment': 'CI/CD',
  rag: 'RAG',
  'retrieval augmented generation': 'RAG',
  'retrieval augmented generation (rag)': 'RAG',
  'rag (retrieval augmented generation)': 'RAG',
  'rest api': 'REST API',
  'rest apis': 'REST API',
  'restful api': 'REST API',
  'restful apis': 'REST API',
  docker: 'Docker',
  kubernetes: 'Kubernetes',
  k8s: 'Kubernetes',
  k8: 'Kubernetes',
  langchain: 'LangChain',
  langgraph: 'LangGraph',
  openai: 'OpenAI',
  'open ai': 'OpenAI',
  redis: 'Redis',
  pinecone: 'Pinecone',
  'pine cone': 'Pinecone',
  git: 'Git',
  github: 'Git',
  gitlab: 'Git',
  python: 'Python',
  django: 'Django',
  fastapi: 'FastAPI',
  'fast api': 'FastAPI',
  java: 'Java',
  'spring boot': 'Spring Boot',
  springboot: 'Spring Boot',
  graphql: 'GraphQL',
  'graph ql': 'GraphQL',
  nestjs: 'NestJS',
  'nest js': 'NestJS',
  'nest.js': 'NestJS',
  mysql: 'MySQL',
  firebase: 'Firebase',
  'socket.io': 'Socket.IO',
  socketio: 'Socket.IO',
  'socket io': 'Socket.IO',
  azure: 'Azure',
  gcp: 'GCP',
  'google cloud': 'GCP',
  'google cloud platform': 'GCP',
  html5: 'HTML5',
  'html 5': 'HTML5',
  css3: 'CSS3',
  'css 3': 'CSS3',
  redux: 'Redux',
  websockets: 'WebSockets',
  'web sockets': 'WebSockets',
  'web-sockets': 'WebSockets',
  microservices: 'Microservices',
  'micro services': 'Microservices',
  'micro-services': 'Microservices',
  linux: 'Linux',
  rbac: 'RBAC',
  'role-based access control': 'RBAC',
  'role based access control': 'RBAC',
  'ai ml': 'AI/ML',
  'ai/ml': 'AI/ML',
  'machine learning': 'AI/ML',
  'backend services': 'Backend Services',
  'backend engineering': 'Backend Services',
  'backend development': 'Backend Services',
};

export const CANONICAL_SKILLS = Array.from(new Set(Object.values(SKILL_ALIASES))).sort((a, b) =>
  a.localeCompare(b, undefined, { sensitivity: 'base' }),
);

export function toCanonical(skill: string): string {
  const key = skill
    .trim()
    .toLowerCase()
    .replace(/[.\s-/]+/g, ' ');
  return SKILL_ALIASES[key] ?? skill.trim();
}

export function isCanonical(skillName: string): boolean {
  return CANONICAL_SKILLS.includes(skillName);
}
