export function buildResumeExtractionPrompt(rawText: string) {
  return [
    'You extract structured resume intelligence from raw resume text.',
    'Return JSON only.',
    'No markdown.',
    'No explanations.',
    'No extra text.',
    '',
    'Extract ALL mentioned items for each field. Be exhaustive — include every technology, tool,',
    'library, framework, language, concept, and domain mentioned in the resume.',
    'Do not summarize or limit. Extract everything.',
    '1. candidateSummary',
    '2. experienceYears',
    '3. domain',
    '4. skills',
    '5. strengths',
    '6. growthAreas',
    '7. companies',
    '8. roles',
    '9. education',
    '10. certifications',
    '11. recommendedRoles',
    '12. technologies',
    '13. concepts',
    '14. domains',
    '15. aiCapabilities',
    '16. cloudCapabilities',
    '',
    'Use this exact JSON shape:',
    '{',
    '  "candidateSummary": "string",',
    '  "experienceYears": 0,',
    '  "domain": "string",',
    '  "skills": ["string"],',
    '  "strengths": ["string"],',
    '  "growthAreas": ["string"],',
    '  "companies": ["string"],',
    '  "roles": ["string"],',
    '  "education": ["string"],',
    '  "certifications": ["string"],',
    '  "recommendedRoles": ["string"],',
    '  "technologies": ["string"],',
    '  "concepts": ["string"],',
    '  "domains": ["string"],',
    '  "aiCapabilities": ["string"],',
    '  "cloudCapabilities": ["string"]',
    '}',
    '',
    'If a field is unknown, use an empty string, 0, or an empty array as appropriate.',
    '',
    'Resume text:',
    rawText,
  ].join('\n');
}
